/*
 * gpio.c
 *
 *  Created on: Sep 15, 2015
 *      Author: Hill
 */

#include "gpio.h"

void GPIO_Init(void)
{
	CONFIG_PIN_AS_GPIO(A,PTB0,OUTPUT);
	CONFIG_PIN_AS_GPIO(B,PTF3,OUTPUT);
	CONFIG_PIN_AS_GPIO(B,PTF2,OUTPUT);
	CONFIG_PIN_AS_GPIO(A,PTA7,OUTPUT);
	CONFIG_PIN_AS_GPIO(A,PTB1,OUTPUT);
	CONFIG_PIN_AS_GPIO(A,PTA1,OUTPUT);
	
	CONFIG_PIN_AS_GPIO(A,PTD1,INPUT);
	CONFIG_PIN_AS_GPIO(A,PTD0,INPUT);
	CONFIG_PIN_AS_GPIO(B,PTH7,INPUT);
	CONFIG_PIN_AS_GPIO(A,PTA2,INPUT);
	CONFIG_PIN_AS_GPIO(A,PTA3,INPUT);
	CONFIG_PIN_AS_GPIO(A,PTB2,INPUT);
	CONFIG_PIN_AS_GPIO(A,PTB3,INPUT);
	CONFIG_PIN_AS_GPIO(B,PTF4,INPUT);
	CONFIG_PIN_AS_GPIO(B,PTF5,INPUT);
	CONFIG_PIN_AS_GPIO(B,PTF6,INPUT);
	
	ENABLE_INPUT(A,PTD1);
	ENABLE_INPUT(A,PTD0);
	ENABLE_INPUT(B,PTH7);
	ENABLE_INPUT(A,PTA2);
	ENABLE_INPUT(A,PTA3);
	ENABLE_INPUT(A,PTB2);
	ENABLE_INPUT(A,PTB3);
	ENABLE_INPUT(B,PTF4);
	ENABLE_INPUT(B,PTF5);
	ENABLE_INPUT(B,PTF6);
	
}
